AWSTemplateFormatVersion: '2010-09-09'
Description: >
  This template creates a dedicated IAM Service Role for CloudFormation.
  This role grants permissions to create, update, and delete CloudFormation
  stacks and their resources. It follows the principle of least privilege
  by allowing only the necessary actions for stack management.
  This role requires an existing master/IDP stack to be already deployed
  as it only operates on stacks with the IDP prefix.

Parameters:
  ExistingIDPStackName:
    Type: String
    Description: Name of an existing IDP stack (must start with IDP or idp). It is assumed that the administrator has deployed the first IDP solution deployment.
    AllowedPattern: '^[Ii][Dd][Pp][a-zA-Z0-9-]*$'
    ConstraintDescription: Must be an existing stack name starting with IDP or idp
  
Resources:
  AllPatternsDeployerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: 'All-Patterns-Deployer-Role-Secure'
      Description: 'Minimal secure role for deploying all GenAI IDP patterns'
      MaxSessionDuration: 3600
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: 'cloudformation.amazonaws.com'
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: CloudFormationPermissions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'cloudformation:*'
                Resource: !Sub 'arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/*/*'
                Condition:
                  StringLike:
                    'cloudformation:StackName': 
                      - !Sub '${ExistingIDPStackName}*'
                      - 'IDP*'
                      - 'idp*'
              - Effect: Allow
                Action:
                  - 'cloudformation:CreateChangeSet'
                Resource: 
                  - 'arn:aws:cloudformation:*:aws:transform/Serverless-2016-10-31'
                  - 'arn:aws:cloudformation:*:aws:transform/Serverless-2016-10-31-*'
              - Effect: Allow
                Action:
                  - 'iam:GetRole'
                  - 'iam:GetRolePolicy'
                  - 'iam:ListRolePolicies'
                  - 'iam:ListAttachedRolePolicies'
                  - 'iam:CreateRole'
                  - 'iam:DeleteRole'
                  - 'iam:AttachRolePolicy'
                  - 'iam:DetachRolePolicy'
                  - 'iam:PutRolePolicy'
                  - 'iam:DeleteRolePolicy'
                  - 'iam:UpdateRole'
                  - 'iam:UpdateRoleDescription'
                  - 'iam:UpdateAssumeRolePolicy'
                  - 'iam:TagRole'
                  - 'iam:CreateServiceLinkedRole'
                  - 'lambda:*'
                  - 'kms:*'
                  - 'logs:*'
                  - 'cloudwatch:*'
                  - 'events:*'
                  - 'sts:AssumeRole'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 's3:*'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 'dynamodb:*'
                Resource: '*'
              - Effect: Deny
                Action: '*'
                Resource: '*'
                Condition:
                  StringNotEquals:
                    'aws:RequestedRegion': !Ref 'AWS::Region'
        - PolicyName: ServicesPermissions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'bedrock:*'
                  - 'textract:*'
                  - 'sagemaker:*'
                  - 'states:*'
                  - 'apigateway:*'
                  - 'appsync:*'
                  - 'cognito-idp:*'
                  - 'cognito-identity:*'
                  - 'glue:*'
                  - 'aoss:*'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 'cloudfront:*'
                  - 'wafv2:*'
                  - 'sns:*'
                  - 'sqs:*'
                  - 'ssm:*'
                  - 'codebuild:*'
                  - 'application-autoscaling:*'
                  - 'scheduler:*'
                  - 'ec2:CreateVpc'
                  - 'ec2:DeleteVpc'
                  - 'ec2:DescribeVpcs'
                  - 'ec2:CreateSubnet'
                  - 'ec2:DeleteSubnet'
                  - 'ec2:DescribeSubnets'
                  - 'ec2:CreateSecurityGroup'
                  - 'ec2:DeleteSecurityGroup'
                  - 'ec2:DescribeSecurityGroups'
                  - 'ec2:AuthorizeSecurityGroupIngress'
                  - 'ec2:AuthorizeSecurityGroupEgress'
                  - 'ec2:RevokeSecurityGroupIngress'
                  - 'ec2:RevokeSecurityGroupEgress'
                  - 'ec2:CreateTags'
                  - 'ec2:DeleteTags'
                  - 'ec2:DescribeTags'
                  - 'ec2:DescribeAvailabilityZones'
                Resource: '*'


Outputs:
  AllPatternsDeployerRoleSecureArn:
    Description: ARN of the All-Patterns-Deployer-Role-Secure
    Value: !GetAtt AllPatternsDeployerRole.Arn